package com.example.ugcssample

import java.lang.Exception

/**
 * Represents an error generated by DJI MSDK without any details.
 */
class DjiUnknownException: Exception("DJI MSDK operation failed due to an unknown error.")